/*
 * Static DLL dispatch for PC build.
 *
 * On GC, REL modules are loaded dynamically via DVD and linked at runtime.
 * On PC, all REL modules are compiled statically with prefixed symbols.
 * This file provides the dispatch table mapping overlay IDs to their
 * prolog/epilog functions.
 *
 * Each REL directory is compiled with -DDLL_ID=<name>, and executor.c
 * (under TARGET_PC) expands _prolog/_epilog/ObjectSetup to prefixed names.
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "game/object.h"
#include "game/dvd.h"
#include "game/memory.h"

typedef s32 (*DLLProlog)(void);
typedef void (*DLLEpilog)(void);

/* ---- Forward declarations for all REL module prolog/epilog ---- */
/* These are generated by the DLL_ID prefix mechanism in executor.c */

#define DECLARE_REL(name) \
    extern s32 name##__prolog(void); \
    extern void name##__epilog(void);

DECLARE_REL(_minigameDLL)
DECLARE_REL(bootDll)
DECLARE_REL(E3setupDLL)
DECLARE_REL(instDll)
DECLARE_REL(m300dll)
DECLARE_REL(m302dll)
DECLARE_REL(m303dll)
DECLARE_REL(m330dll)
DECLARE_REL(m333dll)
DECLARE_REL(m401Dll)
DECLARE_REL(m402Dll)
DECLARE_REL(m403Dll)
DECLARE_REL(m404Dll)
DECLARE_REL(m405Dll)
DECLARE_REL(m406Dll)
DECLARE_REL(m407dll)
DECLARE_REL(m408Dll)
DECLARE_REL(m409Dll)
DECLARE_REL(m410Dll)
DECLARE_REL(m411Dll)
DECLARE_REL(m412Dll)
DECLARE_REL(m413Dll)
DECLARE_REL(m414Dll)
DECLARE_REL(m415Dll)
DECLARE_REL(m416Dll)
DECLARE_REL(m417Dll)
DECLARE_REL(m418Dll)
DECLARE_REL(m419Dll)
DECLARE_REL(m420dll)
DECLARE_REL(m421Dll)
DECLARE_REL(m422Dll)
DECLARE_REL(m423Dll)
DECLARE_REL(m424Dll)
DECLARE_REL(m425Dll)
DECLARE_REL(m426Dll)
DECLARE_REL(m427Dll)
DECLARE_REL(m428Dll)
DECLARE_REL(m429Dll)
DECLARE_REL(m430Dll)
DECLARE_REL(m431Dll)
DECLARE_REL(m432Dll)
DECLARE_REL(m433Dll)
DECLARE_REL(m434Dll)
DECLARE_REL(m435Dll)
DECLARE_REL(m436Dll)
DECLARE_REL(m437Dll)
DECLARE_REL(m438Dll)
DECLARE_REL(m439Dll)
DECLARE_REL(m440Dll)
DECLARE_REL(m441Dll)
DECLARE_REL(m442Dll)
DECLARE_REL(m443Dll)
DECLARE_REL(m444dll)
DECLARE_REL(m445Dll)
DECLARE_REL(m446Dll)
DECLARE_REL(m447dll)
DECLARE_REL(m448Dll)
DECLARE_REL(m449Dll)
DECLARE_REL(m450Dll)
DECLARE_REL(m451Dll)
DECLARE_REL(m453Dll)
DECLARE_REL(m455Dll)
DECLARE_REL(m456Dll)
DECLARE_REL(m457Dll)
DECLARE_REL(m458Dll)
DECLARE_REL(m459dll)
DECLARE_REL(m460Dll)
DECLARE_REL(m461Dll)
DECLARE_REL(m462Dll)
DECLARE_REL(m463Dll)
DECLARE_REL(mentDll)
DECLARE_REL(messDll)
DECLARE_REL(mgmodedll)
DECLARE_REL(modeltestDll)
DECLARE_REL(modeseldll)
DECLARE_REL(mpexDll)
DECLARE_REL(msetupdll)
DECLARE_REL(mstory2Dll)
DECLARE_REL(mstory3Dll)
DECLARE_REL(mstory4Dll)
DECLARE_REL(mstoryDll)
DECLARE_REL(nisDll)
DECLARE_REL(option)
DECLARE_REL(present)
DECLARE_REL(resultDll)
DECLARE_REL(safDll)
DECLARE_REL(selmenuDll)
DECLARE_REL(staffDll)
DECLARE_REL(subchrselDll)
DECLARE_REL(w01Dll)
DECLARE_REL(w02Dll)
DECLARE_REL(w03Dll)
DECLARE_REL(w04Dll)
DECLARE_REL(w05Dll)
DECLARE_REL(w06Dll)
DECLARE_REL(w10Dll)
DECLARE_REL(w20Dll)
DECLARE_REL(w21Dll)
DECLARE_REL(ztardll)

/* ---- REL name-to-function dispatch table ---- */
typedef struct {
    const char *rel_path;  /* as it appears in ovl_table.h */
    DLLProlog prolog;
    DLLEpilog epilog;
} DLLDispatchEntry;

#define ENTRY(name, path) { path, name##__prolog, name##__epilog }

static const DLLDispatchEntry g_dll_table[] = {
    ENTRY(_minigameDLL, "dll/_minigameDLL.rel"),
    ENTRY(bootDll,      "dll/bootdll.rel"),
    ENTRY(E3setupDLL,   "dll/e3setupDLL.rel"),
    ENTRY(instDll,      "dll/instdll.rel"),
    ENTRY(m300dll, "dll/m300dll.rel"),
    ENTRY(m302dll, "dll/m302dll.rel"),
    ENTRY(m303dll, "dll/m303dll.rel"),
    ENTRY(m330dll, "dll/m330dll.rel"),
    ENTRY(m333dll, "dll/m333dll.rel"),
    ENTRY(m401Dll, "dll/m401dll.rel"),
    ENTRY(m402Dll, "dll/m402dll.rel"),
    ENTRY(m403Dll, "dll/m403dll.rel"),
    ENTRY(m404Dll, "dll/m404dll.rel"),
    ENTRY(m405Dll, "dll/m405dll.rel"),
    ENTRY(m406Dll, "dll/m406dll.rel"),
    ENTRY(m407dll, "dll/m407dll.rel"),
    ENTRY(m408Dll, "dll/m408dll.rel"),
    ENTRY(m409Dll, "dll/m409dll.rel"),
    ENTRY(m410Dll, "dll/m410dll.rel"),
    ENTRY(m411Dll, "dll/m411dll.rel"),
    ENTRY(m412Dll, "dll/m412dll.rel"),
    ENTRY(m413Dll, "dll/m413dll.rel"),
    ENTRY(m414Dll, "dll/m414dll.rel"),
    ENTRY(m415Dll, "dll/m415dll.rel"),
    ENTRY(m416Dll, "dll/m416dll.rel"),
    ENTRY(m417Dll, "dll/m417dll.rel"),
    ENTRY(m418Dll, "dll/m418dll.rel"),
    ENTRY(m419Dll, "dll/m419dll.rel"),
    ENTRY(m420dll, "dll/m420dll.rel"),
    ENTRY(m421Dll, "dll/m421dll.rel"),
    ENTRY(m422Dll, "dll/m422dll.rel"),
    ENTRY(m423Dll, "dll/m423dll.rel"),
    ENTRY(m424Dll, "dll/m424dll.rel"),
    ENTRY(m425Dll, "dll/m425dll.rel"),
    ENTRY(m426Dll, "dll/m426dll.rel"),
    ENTRY(m427Dll, "dll/m427dll.rel"),
    ENTRY(m428Dll, "dll/m428dll.rel"),
    ENTRY(m429Dll, "dll/m429dll.rel"),
    ENTRY(m430Dll, "dll/m430dll.rel"),
    ENTRY(m431Dll, "dll/m431dll.rel"),
    ENTRY(m432Dll, "dll/m432dll.rel"),
    ENTRY(m433Dll, "dll/m433dll.rel"),
    ENTRY(m434Dll, "dll/m434dll.rel"),
    ENTRY(m435Dll, "dll/m435dll.rel"),
    ENTRY(m436Dll, "dll/m436dll.rel"),
    ENTRY(m437Dll, "dll/m437dll.rel"),
    ENTRY(m438Dll, "dll/m438dll.rel"),
    ENTRY(m439Dll, "dll/m439dll.rel"),
    ENTRY(m440Dll, "dll/m440dll.rel"),
    ENTRY(m441Dll, "dll/m441dll.rel"),
    ENTRY(m442Dll, "dll/m442dll.rel"),
    ENTRY(m443Dll, "dll/m443dll.rel"),
    ENTRY(m444dll, "dll/m444dll.rel"),
    ENTRY(m445Dll, "dll/m445dll.rel"),
    ENTRY(m446Dll, "dll/m446dll.rel"),
    ENTRY(m447dll, "dll/m447dll.rel"),
    ENTRY(m448Dll, "dll/m448dll.rel"),
    ENTRY(m449Dll, "dll/m449dll.rel"),
    ENTRY(m450Dll, "dll/m450dll.rel"),
    ENTRY(m451Dll, "dll/m451dll.rel"),
    ENTRY(m453Dll, "dll/m453dll.rel"),
    ENTRY(m455Dll, "dll/m455dll.rel"),
    ENTRY(m456Dll, "dll/m456dll.rel"),
    ENTRY(m457Dll, "dll/m457dll.rel"),
    ENTRY(m458Dll, "dll/m458dll.rel"),
    ENTRY(m459dll, "dll/m459dll.rel"),
    ENTRY(m460Dll, "dll/m460dll.rel"),
    ENTRY(m461Dll, "dll/m461dll.rel"),
    ENTRY(m462Dll, "dll/m462dll.rel"),
    ENTRY(m463Dll, "dll/m463dll.rel"),
    ENTRY(mentDll,      "dll/mentdll.rel"),
    ENTRY(messDll,      "dll/messdll.rel"),
    ENTRY(mgmodedll,    "dll/mgmodedll.rel"),
    ENTRY(modeltestDll, "dll/modeltestdll.rel"),
    ENTRY(modeseldll,   "dll/modeseldll.rel"),
    ENTRY(mpexDll,      "dll/mpexdll.rel"),
    ENTRY(msetupdll,    "dll/msetupdll.rel"),
    ENTRY(mstory2Dll,   "dll/mstory2dll.rel"),
    ENTRY(mstory3Dll,   "dll/mstory3dll.rel"),
    ENTRY(mstory4Dll,   "dll/mstory4dll.rel"),
    ENTRY(mstoryDll,    "dll/mstorydll.rel"),
    ENTRY(nisDll,       "dll/nisdll.rel"),
    ENTRY(option,       "dll/option.rel"),
    ENTRY(present,      "dll/present.rel"),
    ENTRY(resultDll,    "dll/resultdll.rel"),
    ENTRY(safDll,       "dll/safdll.rel"),
    ENTRY(selmenuDll,   "dll/selmenuDLL.rel"),
    ENTRY(staffDll,     "dll/staffdll.rel"),
    ENTRY(subchrselDll, "dll/subchrseldll.rel"),
    ENTRY(w01Dll, "dll/w01dll.rel"),
    ENTRY(w02Dll, "dll/w02dll.rel"),
    ENTRY(w03Dll, "dll/w03dll.rel"),
    ENTRY(w04Dll, "dll/w04dll.rel"),
    ENTRY(w05Dll, "dll/w05dll.rel"),
    ENTRY(w06Dll, "dll/w06dll.rel"),
    ENTRY(w10Dll, "dll/w10dll.rel"),
    ENTRY(w20Dll, "dll/w20dll.rel"),
    ENTRY(w21Dll, "dll/w21dll.rel"),
    ENTRY(ztardll, "dll/ztardll.rel"),
    { NULL, NULL, NULL }
};

#define DLL_TABLE_SIZE (sizeof(g_dll_table) / sizeof(g_dll_table[0]) - 1)

/* ---- Helper: find dispatch entry by REL path ---- */
static const DLLDispatchEntry *find_dispatch(const char *rel_path) {
    /* Case-insensitive prefix match on the path */
    for (int i = 0; i < (int)DLL_TABLE_SIZE; i++) {
        if (strcasecmp(g_dll_table[i].rel_path, rel_path) == 0) {
            return &g_dll_table[i];
        }
    }
    return NULL;
}

/* ================================================================
 * Replacement for objdll.c functions
 * ================================================================ */

omDllData *omDLLinfoTbl[OM_DLL_MAX];
static FileListEntry *omDLLFileList;

void omDLLDBGOut(void) {
    OSReport("DLL DBG OUT\n");
}

void omDLLInit(FileListEntry *ovl_list) {
    s32 i;
    OSReport("[PC-DLL] omDLLInit\n");
    for (i = 0; i < OM_DLL_MAX; i++) {
        omDLLinfoTbl[i] = NULL;
    }
    omDLLFileList = ovl_list;
}

s32 omDLLStart(s16 overlay, s16 flag) {
    s32 dllno;
    OSReport("[PC-DLL] omDLLStart %d %d\n", overlay, flag);

    dllno = omDLLSearch(overlay);
    if (dllno >= 0 && !flag) {
        omDllData *dll = omDLLinfoTbl[dllno];
        OSReport("[PC-DLL] Already loaded %s, calling prolog\n", dll->name);

        /* Find and call prolog directly */
        const DLLDispatchEntry *entry = find_dispatch(dll->name);
        if (entry && entry->prolog) {
            dll->ret = entry->prolog();
        }
        return dllno;
    }

    /* Find free slot */
    for (dllno = 0; dllno < OM_DLL_MAX; dllno++) {
        if (omDLLinfoTbl[dllno] == NULL) break;
    }
    if (dllno == OM_DLL_MAX) return -1;

    omDLLLink(&omDLLinfoTbl[dllno], overlay, TRUE);
    return dllno;
}

void omDLLNumEnd(s16 overlay, s16 flag) {
    s16 dllno;
    if (overlay < 0) {
        OSReport("[PC-DLL] omDLLNumEnd Invalid dllno %d\n", overlay);
        return;
    }
    dllno = omDLLSearch(overlay);
    if (dllno < 0) {
        OSReport("[PC-DLL] omDLLNumEnd not found DLL No%d\n", overlay);
        return;
    }
    omDLLEnd(dllno, flag);
}

void omDLLEnd(s16 dllno, s16 flag) {
    OSReport("[PC-DLL] omDLLEnd %d %d\n", dllno, flag);
    if (flag == 1) {
        omDLLUnlink(omDLLinfoTbl[dllno], 1);
        omDLLinfoTbl[dllno] = NULL;
    } else {
        omDllData *dll = omDLLinfoTbl[dllno];
        const DLLDispatchEntry *entry = find_dispatch(dll->name);
        if (entry && entry->epilog) {
            entry->epilog();
        }
    }
}

omDllData *omDLLLink(omDllData **dll_ptr, s16 overlay, s16 flag) {
    FileListEntry *dllFile = &omDLLFileList[overlay];
    OSReport("[PC-DLL] Link DLL: %s\n", dllFile->name);

    omDllData *dll = (omDllData *)HuMemDirectMalloc(HEAP_SYSTEM, sizeof(omDllData));
    *dll_ptr = dll;
    dll->name = dllFile->name;
    dll->module = NULL; /* No module data on PC - statically linked */
    dll->bss = NULL;
    dll->ret = 0;

    if (flag == 1) {
        const DLLDispatchEntry *entry = find_dispatch(dllFile->name);
        if (entry && entry->prolog) {
            OSReport("[PC-DLL] %s prolog start\n", dllFile->name);
            dll->ret = entry->prolog();
            OSReport("[PC-DLL] %s prolog end\n", dllFile->name);
        } else {
            OSReport("[PC-DLL] WARNING: No dispatch entry for %s\n", dllFile->name);
        }
    }

    return dll;
}

void omDLLUnlink(omDllData *dll_ptr, s16 flag) {
    OSReport("[PC-DLL] Unlink DLL: %s\n", dll_ptr->name);
    if (flag == 1) {
        const DLLDispatchEntry *entry = find_dispatch(dll_ptr->name);
        if (entry && entry->epilog) {
            entry->epilog();
        }
    }
    HuMemDirectFree(dll_ptr);
}

s32 omDLLSearch(s16 overlay) {
    FileListEntry *dllFile = &omDLLFileList[overlay];
    for (int i = 0; i < OM_DLL_MAX; i++) {
        omDllData *dll = omDLLinfoTbl[i];
        if (dll != NULL && strcmp(dll->name, dllFile->name) == 0) {
            return i;
        }
    }
    return -1;
}

void omDLLInfoDump(OSModuleInfo *module) { (void)module; }
void omDLLHeaderDump(OSModuleHeader *module) { (void)module; }
